# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{slugged}
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Darcy Laycock"]
  s.date = %q{2010-12-30}
  s.description = %q{Super simple slugs for ActiveRecord 3.0 and higher, with support for slug history}
  s.email = %q{sutto@sutto.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rvmrc",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "lib/generators/slugged/slug_migration/slug_migration_generator.rb",
     "lib/generators/slugged/slug_migration/templates/migration.erb",
     "lib/generators/slugged/slugs/slugs_generator.rb",
     "lib/generators/slugged/slugs/templates/migration.erb",
     "lib/slugged.rb",
     "lib/slugged/active_record_methods.rb",
     "lib/slugged/caching.rb",
     "lib/slugged/finders.rb",
     "lib/slugged/memory_cache.rb",
     "lib/slugged/railtie.rb",
     "lib/slugged/scopes.rb",
     "lib/slugged/slug.rb",
     "lib/slugged/slug_history.rb",
     "lib/slugged/version.rb",
     "metrics/.gitignore",
     "slugged.gemspec",
     "test/caching_test.rb",
     "test/helper.rb",
     "test/is_sluggable_test.rb",
     "test/model_definitions.rb",
     "test/slug_history_test.rb",
     "test/slugged_test.rb"
  ]
  s.homepage = %q{http://github.com/Sutto/slugged}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Super simple slugs for ActiveRecord 3.0 and higher, with support for slug history}
  s.test_files = [
    "test/caching_test.rb",
     "test/helper.rb",
     "test/is_sluggable_test.rb",
     "test/model_definitions.rb",
     "test/slug_history_test.rb",
     "test/slugged_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<uuid>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<reversible_data>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<uuid>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<reversible_data>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<uuid>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<reversible_data>, [">= 0"])
  end
end

